version: '3.9'
services:
  model-scanner:
    image: civitai-model-scanner
    build:
      context: ./model-scanner/
      dockerfile: Dockerfile
  orchestrator:
    image: civitai-model-scanner-orchestrator
    build:
      context: ./orchestrator/ModelScanner/
      dockerfile: Dockerfile
    restart: always
    environment:
      - "ConnectionStrings:JobStorage=/data/new-jobs.db"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - db:/data/
    ports:
      - "80:8080"
    depends_on:
      - model-scanner
volumes:
  db:
